//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JitJotData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Binary
    {
        public Binary()
        {
            this.CodeUnitDllReferences = new HashSet<CodeUnitDllReference>();
            this.CompilerOutputs = new HashSet<CompilerOutput>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] RawAssembly { get; set; }
        public Nullable<int> Type { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string RuntimeVersion { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<CodeUnitDllReference> CodeUnitDllReferences { get; set; }
        public virtual ICollection<CompilerOutput> CompilerOutputs { get; set; }
    }
}
