//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JitJotData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeUnit
    {
        public CodeUnit()
        {
            this.AdminSettings = new HashSet<AdminSetting>();
            this.CodeUnitDllReferences = new HashSet<CodeUnitDllReference>();
            this.CompilerOutputs = new HashSet<CompilerOutput>();
            this.RuntimeUserConfigs = new HashSet<RuntimeUserConfig>();
        }
    
        public System.Guid Id { get; set; }
        public long AutoId { get; set; }
        public long VersionId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Source { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool IsPublic { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ICollection<AdminSetting> AdminSettings { get; set; }
        public virtual CodeUnitAutoId CodeUnitAutoId { get; set; }
        public virtual ICollection<CodeUnitDllReference> CodeUnitDllReferences { get; set; }
        public virtual Language Language { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CompilerOutput> CompilerOutputs { get; set; }
        public virtual ICollection<RuntimeUserConfig> RuntimeUserConfigs { get; set; }
    }
}
