//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JitJotData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dotcodedbEntities : DbContext
    {
        public dotcodedbEntities()
            : base("name=dotcodedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminSetting> AdminSettings { get; set; }
        public DbSet<Binary> Binaries { get; set; }
        public DbSet<BinaryType> BinaryTypes { get; set; }
        public DbSet<CodeUnitAutoId> CodeUnitAutoIds { get; set; }
        public DbSet<CodeUnitDllReference> CodeUnitDllReferences { get; set; }
        public DbSet<CodeUnit> CodeUnits { get; set; }
        public DbSet<CompilerOutput> CompilerOutputs { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<RunLog> RunLogs { get; set; }
        public DbSet<RuntimeUserConfig> RuntimeUserConfigs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
