//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JitJotData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunLog
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CodeUnitId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Input { get; set; }
        public string Output { get; set; }
        public string IPAddress { get; set; }
    }
}
