//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JitJotData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuntimeUserConfig
    {
        public System.Guid Id { get; set; }
        public System.Guid CodeUnitId { get; set; }
        public string Namespace { get; set; }
        public string Method { get; set; }
        public string JsonArgs { get; set; }
        public string ReturnAttribute { get; set; }
    
        public virtual CodeUnit CodeUnit { get; set; }
    }
}
